### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by MattHeffNT** [Hacksore/react-skinview3d#15]
Hey Hacksore,

I would love to be able to use your React Skinview3D as a component in a project I'm working on. however, I'm getting an error saying that it can't find the module when trying to launch my React App server, even after I have installed into it my local project. 

"Module not found: Can't resolve 'react-skinview3d"

Thanks heaps, look forward to chatting with you.

Matt

**Comment by Hacksore** [comment]
Yeah I def broke the rollup bundle in 2.x so let's skip to 3.x which changes a bit.

Please try `3.0.0-alpha1` and report back if all is working well.

**Comment by MattHeffNT** [comment]
hello Hacksore, thank you for responding. I think one of my issues might be is that I'm trying to import into a React project built in Webpack (I'm just using the create-react-app config). 

I'm no longer getting the "can't find module" error, I did start getting a "duplicate" react error though, I've seemed to be able to mitigate this by doing an npm install inside the react-skinview3d folder inside my node_modules....however this is now giving me an "uncaught (in promise) Event {isTrusted: true, type: 'error', target: null, currentTarget: null, eventPhase: 0, …}" error in the console now.

Kind regards,

Matt

**Comment by Hacksore** [comment]
@MattHeffNT Had a quick test on CSB and seems to work but their setup is a bit custom.

https://codesandbox.io/s/react-skinview3d-r5zt0?file=/src/App.js

**Comment by Hacksore** [comment]
@MattHeffNT I did publish a new alpha to try out - I moved react to a peer dep so that should help with the multiple react versions problem hopefully.

`react-skinview3d@3.0.0-alpha2`

**Comment by MattHeffNT** [comment]
Thanks @Hacksore , for some reason, when I start with a create-react-app and try to import Skinview3d I was getting an uncaught promise error. However, I've just downloaded the zip file from your codesandbox and installed it, and it seems to work fine.

**Comment by Hacksore** [comment]
@MattHeffNT I'll close out this issue but if you run into anything else you can open a new one.
