### ISSUE TITLE
Panorama support

### ISSUE THREAD

**Issue by AlexanderMatveev** [Hacksore/react-skinview3d#164]
See https://github.com/bs-community/skinview3d#usage:

```js
// Set the background to a panoramic image
skinViewer.loadPanorama("img/panorama1.png");
```

**Comment by AlexanderMatveev** [comment]
Works by setting `SkinViewerOptions`:

```jsx
import Panorama from '../../assets/panorama.png';
<ReactSkinview3d
    // ...
    options={{
        // ...
        panorama: {
            src: Panorama
        },
    }}
/>
```

**Comment by Hacksore** [comment]
An alternative approach would be if you needed access to the skinviewer object outside of first mount/render would be use a `onReady` and a ref.

Example CSB.
https://codesandbox.io/p/sandbox/react-skinvew3d-onready-ref-xddtnf?file=%2Fsrc%2FApp.tsx%3A1%2C1
