### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by mrvnnn** [Hacksore/react-skinview3d#168]
cant use the package on my project. Have a clean and new react app and want to use it, followed your steps thats only to install the one, but i only got errors. "ENOENT: no such file or directory, open '\node_modules\skinview3d\src\model.ts"

**Comment by Hacksore** [comment]
If you're able to share more information then it would be possible for me to help.

 - how are you using react
 - what package manager
 - what operating system
 - what nodejs version
 - etc

**Comment by mrvnnn** [comment]
I created a new Project like this: 

1. npx create-react-app test--template typescript
2. npm install react-skinview3d
3. added your demo code
4. npm start

and then nothing worked

**Comment by Hacksore** [comment]
seems working on my end, there are some build issues but they don't block anything.

demo cra repo: https://github.com/Hacksore/sv3d-cra

FWIW I don't recommend using CRA and probably best to move over to https://vitejs.dev/
