### ISSUE TITLE
Bug on first and second map skin

### ISSUE THREAD

**Issue by Fakepng** [Hacksore/react-skinview3d#17]
![image](https://user-images.githubusercontent.com/86796781/158780592-f7a23406-6f1d-4fb6-9300-6932681fa0cc.png)
![image](https://user-images.githubusercontent.com/86796781/158780681-213db6a5-f8e2-4ea2-83e8-3508c6942ded.png)
![image](https://user-images.githubusercontent.com/86796781/158780738-8b1bb03d-1d6d-49fe-86ea-e6ffc86376d8.png)

**Comment by Hacksore** [comment]
@Fakepng a codesandbox for reproduction would be helpful here

**Comment by Hacksore** [comment]
Closing is stale, please open a new issue if the problem still exists.
