### ISSUE TITLE
Error: require() of ES Module, NextJS

### ISSUE THREAD

**Issue by andreihalt** [Hacksore/react-skinview3d#18]
Getting:

Error: require() of ES Module E:\skinview3d\myapp\node_modules\skinview3d\libs\skinview3d.js from E:\skinview3d\myapp\node_modules\react-skinview3d\dist\index.js not supported.
Instead change the require of skinview3d.js in E:\skinview3d\myapp\node_modules\react-skinview3d\dist\index.js to a dynamic import() which is available in all CommonJS modules.

With react-skinview3d whilst using NextJS

Sandbox:

https://codesandbox.io/s/determined-varahamihira-62ms17?file=/pages/index.js

**Comment by Hacksore** [comment]
I don't have the bandwidth right now but if anyone has time to look into this and raise a PR I'd be happy to review and merge.

Might be something @g-plane could provide some insight to.

The upstream issue for the framework bindings https://github.com/bs-community/skinview3d/issues/107

**Comment by Hacksore** [comment]
This seems like a working solution from my minimal testing.
https://codesandbox.io/s/react-skinview3d-next-esm-7n2eh1?file=/pages/index.js

Followed this thread https://github.com/vercel/next.js/issues/25454

**Comment by andreihalt** [comment]
yes, this works for me too 👍!  but i have a question.

Can you use controls with JS (not TypeScript)?

im getting "ReferenceError: skinview3d is not defined" when using 
let control = skinview3d.createOrbitControls(skinViewer);

after importing skinview3d

im getting "TypeError: skinview3d.createOrbitControls is not a function"

**Comment by Hacksore** [comment]
@andreihalt I've updated the codesandbox to show how. You need to install `skinview3d` as those functions don't exist in this wrapper lib.

https://codesandbox.io/s/react-skinview3d-next-esm-7n2eh1?file=/pages/index.js
