### ISSUE TITLE
Does not use JSX file extension despite being written in JSX

### ISSUE THREAD

**Issue by haykam821** [Hacksore/react-skinview3d#4]
Despite some files using JSX syntax (`<div></div>`), they use the `.js` extension rather than the proper extension for JSX, `.jsx`.

The following 2 files are affected:

* [src/index.js](https://github.com/Hacksore/react-skinview3d/blob/master/src/index.js)
* [src/stories/skinview3d.stories.js](https://github.com/Hacksore/react-skinview3d/blob/master/src/stories/skinview3d.stories.js)

**Comment by Hacksore** [comment]
Fixed in 068117484ff42f9fe6a6b885fade31f318504f43
